WebApp/Models/Author.cs
namespace WebApp.Models
{
	/// <summary>
	/// Автор проекта.
	/// </summary>
    public class Author
    {
		/// <summary>
		/// Имя.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// Электронная почта.
		/// </summary>
		public string Email { get; set; }
	}
}

WebApp/Models/ErrorViewModel.cs
using System;

namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Models/Student.cs
using System;
using System.ComponentModel.DataAnnotations;
using WebApp.Attributes;
using System.Collections.Generic;

namespace WebApp.Models
{
	/// <summary>
	/// Студент.
	/// </summary>
    public class Student
    {
		/// <summary>
		/// Идентификатор.
		/// </summary>
		[Display(Name = "Идентификатор")]
		public int? Id { get; set; }

		/// <summary>
		/// Имя.
		/// </summary>
		[Display(Name = "Имя")]
		[Required]
		[NameValidation(4, 30, ErrorMessage = "Введено некорректное имя.")]
		public string Name { get; set; }

		/// <summary>
		/// Дата рождения.
		/// </summary>
		[Display(Name = "Дата рождения")]
		[DataType(DataType.Date)]
		public DateTime BirthDate { get; set; }

		/// <summary>
		/// Название группы.
		/// </summary>
		[Display(Name = "Группа")]
		[Required]
		[RegularExpression(@"[А-Я]{1,4}-\d{6}", ErrorMessage = "Название группы не соответствует шаблону.")]
		public string GroupName { get; set; }

		/// <summary>
		/// Названия сданных экзаменов.
		/// </summary>
		[Display(Name = "Сданные экзамены")]
		public List<string> ExaminationNames { get; set; }
	}
}

WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return RedirectPermanent("/Student");
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;
using Microsoft.Extensions.DependencyInjection;
using WebApp.DbContexts;
using System.Linq;
using DbStudent = WebApp.DataModels.Student;

namespace WebApp.Controllers
{
	public class StudentController : Controller
    {
		/// <summary>
		/// Сервис студентов.
		/// </summary>
		private readonly IStudentService _studentService;

		/// <summary>
		/// Конструктор.
		/// </summary>
		/// <param name="student_service">Сервис студентов.</param>
		/// <param name="student_context">Контекст студентов.</param>
		public StudentController(IStudentService student_service)
		{
			_studentService = student_service;
		}

		#region Actions

		/// <summary>
		/// Возвращает представление со списком студентов.
		/// </summary>
		public IActionResult Index() =>
			View("StudentList", _studentService.GetAll().Select(ConvertStudent));

		/// <summary>
		/// Возвращает представление с информацией о студенте.
		/// </summary>
		/// <param name="student_id">Идентификатор студента.</param>
		public IActionResult Details(int student_id) =>
			View("StudentDetails", ConvertStudent(_studentService.Get(student_id)));

		/// <summary>
		/// Добавляет студента.
		/// </summary>
		/// <param name="student">Добавляемый студент.</param>
		[HttpPost]
		public IActionResult Add(Student student)
		{
			if (!ModelState.IsValid)
			{
				return View("StudentEdit", null);
			}
			
			DbStudent db_student = ConvertStudent(student);
			_studentService.Add(db_student);
			return RedirectToAction("Details", new { student_id = db_student.Id });
		}

		/// <summary>
		/// Возвращает представление для добавления студента.
		/// </summary>
		public IActionResult Add() => View("StudentEdit", null);

		/// <summary>
		/// Удаляет студента.
		/// </summary>
		/// <param name="student_id">Идентификатор студента.</param>
		public IActionResult Remove(int student_id)
		{
			_studentService.Remove(student_id);
			return RedirectToAction("Index");
		}

		/// <summary>
		/// Изменяет студента.
		/// </summary>
		/// <param name="student">Отредактированный студент.</param>
		[HttpPost]
		public IActionResult Edit(Student student)
		{
			if (!ModelState.IsValid)
			{
				return View("StudentEdit", student);
			}

			_studentService.Edit(ConvertStudent(student));
			return RedirectToAction("Details", new { student_id = student.Id });
		}

		/// <summary>
		/// Возвращает представление для изменения студента.
		/// </summary>
		/// <param name="student_id">Идентификатор студента.</param>
		public IActionResult Edit(int student_id) =>
			View("StudentEdit", ConvertStudent(_studentService.Get(student_id)));

		#endregion

		#region Methods/Private

		/// <summary>
		/// Преобразует студента.
		/// </summary>
		private DbStudent ConvertStudent(Student student)
		{
			return new DbStudent
			{
				Id = student.Id ?? 0,
				Name = student.Name,
				BirthDate = student.BirthDate,
				GroupName = student.GroupName
			};
		}

		/// <summary>
		/// Преобразует студента.
		/// </summary>
		private Student ConvertStudent(DbStudent student)
		{
			return new Student
			{
				Id = student.Id,
				Name = student.Name,
				BirthDate = student.BirthDate,
				GroupName = student.GroupName,
				ExaminationNames = student.Examinations?
					.Select(e => e.Name)
					.ToList()
			};
		}

		#endregion
	}
}

WebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

WebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

WebApp/Views/Shared/_Layout.cshtml
@inject IOptions<Author> author_options
@{ 
    Author author = author_options.Value;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Student" asp-action="Index">Студенты</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>@author.Name @author.Email</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/Views/Student/StudentDetails.cshtml
@model WebApp.Models.Student

@{
    ViewData["Title"] = "Информация о студенте";
}

<h2>Информация о студенте</h2>

<div>
    <h4>Студент</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ExaminationNames)
        </dt>
        <dd>
            @string.Join(", ", Model.ExaminationNames?.Select(n => $"\"{n}\"") ?? Enumerable.Empty<string>())
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Изменить", "Edit", new { student_id = Model.Id }) |
    <a asp-action="Index">Вернуться к списку</a>
</div>

WebApp/Views/Student/StudentEdit.cshtml
@model WebApp.Models.Student

@{
    ViewData["Title"] = "Редактор студента";
    string group_name_editor_id = "GroupNameEditor";
}

@inject IStudentService _studentService;

@if (Model == null)
{
    <h2>Создать студента</h2>
}
else
{
    <h2>Изменить студента</h2>
}

<h4>Студент</h4>
<hr />
@using (Html.BeginForm(Model == null ? "Edit" : "Add"))
{
    @Html.ValidationSummary(true)
    <div class="row">
        <div class="col-md-4">
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "control-label" })
                @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.BirthDate, new { @class = "control-label" })
                @Html.EditorFor(m => m.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.GroupName, new { @class = "control-label" })
                @Html.EditorFor(m => m.GroupName, new { htmlAttributes = new { @id = group_name_editor_id, @class = "form-control" } })
                <button type="button" class="btn btn-default" onclick="SetRandomGroupName()">Случайная группа</button>
                <div>
                    @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
                </div>
            </div>
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </div>
}

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        function SetRandomGroupName() {
            $("@Html.Raw($"#{group_name_editor_id}")").val("@Html.Raw($"{_studentService.GetRandomGroupName()}")");
        }
    </script>
}

WebApp/Views/Student/StudentList.cshtml
@model IEnumerable<WebApp.Models.Student>

@{
    ViewData["Title"] = "Список студентов";
}

<h2>Список студентов</h2>

<p>
    <a asp-action="Add">Добавить</a>
</p>
@if (Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var student in Model)
    {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => student.Name)
                </td>
                <td>
                    @Html.ActionLink("Изменить", "Edit", new { student_id = student.Id }) |
                    @Html.ActionLink("Подробнее", "Details", new { student_id = student.Id }) |
                    @Html.ActionLink("Удалить", "Remove", new { student_id = student.Id })
                </td>
            </tr>
    }
        </tbody>
    </table>
}
else
{
    <h3>Список пуст</h3>
}